import { PUBLIC_BACKEND_API } from 'src/config-global';

/** Api Endpoints for public api */
export const endpoints = {
  root: PUBLIC_BACKEND_API,
  auth: {
    root: '/auth',
    login: `/login`,
    signup: `/signup`,
    password: {
      change: '/update-password',
      forgot: '/forgot-password',
      reset: '/reset-password',
    },
    email: {
      verify: '/verify-email',
    },
  },
  warehouses: {
    root: '/warehouse',
    list: `/`,
    create: `/`,
    own: `/own`,
    get: (id) => `/${id}`,
    delete: (id) => `/${id}`,
    update: (id) => `/${id}`,
  },
  reviews: {
    root: '/review',
    create: '/',
    delete: (id) => `/${id}`,
    update: (id) => `/${id}`,
  },
  address: {
    root: '/address',
    search: (query) => `/search?search=${query}`,
    create: '/',
    update: '/',
    get: (id) => `/${id}`,
    delete: (id) => `/${id}`,
    google_reviews: `/google-reviews`,
  },
  file_upload: {
    root: '/file-upload',
    list: '/',
    create: '/',
    delete_url: `/file`,
    get: (id) => `/${id}`,
    delete: (id) => `/${id}`,
  },
  admin: {
    root: '/admin',
    warehouse: {
      update: (id) => `/warehouse/${id}`,
    },
    users: {
      list: '/users',
      get: (id) => `/users/${id}`,
      update: (id) => `/users/${id}`,
    },
    transaction: {
      list: '/transaction',
      approve: (id) => `/transactions/approve/${id}`,
      cancel: (id) => `/transactions/cancel/${id}`,
    },
    plan: {
      upgrade: (id) => `/plan/upgrade/${id}`,
    },
  },
  profile: {
    root: '/user/profile',
    update: '/',
    get: '/',
  },
  service: {
    root: '/services',
    list: '/',
    get: (id) => `/${id}`,
    own: `/own`,
    updateOwn: `/own`,
  },
  purchase: {
    root: '/purchase',
    create: '/',
  },
  transaction: {
    root: '/user/transaction',
    list: '/',
    get: (id) => `/${id}`,
    cancel: (id) => `/cancel/${id}`,
    complete: (id) => `/complete/${id}`,
  },
  billing: {
    root: '/user/billing',
    get: '/',
  },
  billing_info: {
    root: '/user/billing-info',
    list: `/`,
    create: '/',
    primary: `/primary`,
    get: (id) => `/${id}`,
    update: (id) => `/${id}`,
    delete: (id) => `/${id}`,
  },
  cards: {
    root: '/user/cards',
    list: '/',
    create: '/',
    primary: `/primary`,
    get: (id) => `/${id}`,
    update: (id) => `/${id}`,
    delete: (id) => `/${id}`,
  },
  ach: {
    root: '/user/ach',
    list: '/',
    create: '/',
    primary: `/primary`,
    get: (id) => `/${id}`,
    update: (id) => `/${id}`,
    delete: (id) => `/${id}`,
  },
  plans: {
    root: '/plans',
    list: '/',
    create: '/',
    get: (id) => `/${id}`,
    upgrade: (id) => `/upgrade/${id}`,
    cancel: `/cancel`,
  },
  invoices: {
    root: '/invoices',
    list: '/',
  },
  blogs: {
    root: '/posts',
    list: '/',
    create: '/',
    get: (id) => `/${id}`,
    update: (id) => `/${id}`,
    delete: (id) => `/${id}`,
  },
  search: {
    root: '/search',
    query: (q) => `?query=${q}`,
    warehouses: (q) => `/warehouses?query=${q}`,
    services: (q) => `/services?query=${q}`,
    users: (q) => `/users?query=${q}`,
  },
  contact_us: {
    root: '/contact-us',
    create: '/',
  },
  notification: {
    root: '/notification',
    list: '/',
    read_all: '/all',
    read: (id) => `/${id}`,
  },
  users: {
    root: '/users',
    get: (id) => `/${id}`,
  },
  payment: {
    root: '/payment',
    plans: '/plans',
    subscription: '/subscription',
    account_refresh_url: '/stripe/accountRefreshUrl',
  },
};
