export const serviceTypes = [
  {
    type: 'Warehouse',
    subtypes: [],
  },
  {
    type: 'Transportation',
    subtypes: [
      'Freight Forwarders',
      'Air Cargo Services',
      'Rail Freight Services',
      'Courier and White Glove Delivery Services',
      'Intermodal Transportation Providers',
      'Last-Mile Delivery Services',
      'Refrigerated Transport Services',
      'Trucking FTL/LTL',
      'Heavy Haul/Oversized Load',
      'Drayage Services',
      'Ocean Freight Services',
      'Freight Consolidators',
      'Customs Brokers',
      'Parcel Carriers',
      'Owner/Operator Trucking',
    ],
  },
  {
    type: 'Software',
    subtypes: [
      'TMS (Transportation Management System)',
      'ERP (Enterprise Resource Planning) Software',
      'WMS (Warehouse Management System',
      'OMS (Order Management System)',
      'Fleet Management Software',
      'Demand Planning Software',
      'Supplier Relationship Management (SRM) Software',
      'Labor Management System (LMS)',
      'Warehouse Automation & Robotics',
      'Dock Scheduling Software',
      'Ecommerce Seller Softwares',
      'Website Development',
      'Photo/Video Software',
    ],
  },
  {
    type: 'Packaging & Supply',
    subtypes: [
      'Packaging Material Suppliers',
      'Custom Packaging & Design',
      'Production Machinery Suppliers',
      'Adhesive and Tape Suppliers',
      'Drum and Barrel Suppliers',
      'Eco-Friendly Packaging Solutions',
      'Forklift & Equipment',
      'Retail Packaging Solutions',
      'Packaging Testing and Quality Assurance Services',
      'Recycling Services',
      'Pallet Suppliers',
    ],
  },
  {
    type: 'Manufacturing/Wholesale',
    subtypes: [
      'Raw Material Suppliers',
      'Electronics Manufacturers',
      'Furniture Manufacturers',
      'Chemical Manufacturers',
      'Food and Beverage Manufacturers',
      'Plastics Manufacturers',
      'Textile Manufacturers',
      'Metal Fabricators',
      'Home Goods Manufacturers',
      'Personal Care Product Manufacturers',
      'Sporting Goods Manufacturers',
      'Medical Equipment Manufacturers',
      'Toy Manufacturers',
      'Cosmetic Product Manufacturers',
      'Wholesalers',
      'Liquidators',
      'Retail Chains',
    ],
  },
  {
    type: 'Marketing/Creative',
    subtypes: [
      'Graphic Design Services',
      'Branding Agencies',
      'Content Marketing Agencies',
      'Social Media Marketing Agencies',
      'Public Relations Agencies',
      'Copywriting Services',
      'Web Design and Development Agencies',
      'Search Engine Optimization (SEO) Agencies',
      'Email Marketing Services',
      'Influencer Marketing Agencies',
      'Event Planning and Management Services',
      'Photography Services',
      'Marketing Automation Services',
      'Trade Shows & Events',
      'Podcast Production Services',
      'Media Buying and Planning Agencies',
      'User Experience (UX) Design Services',
      'SMS Marketing Services',
      'Merchandising and Promotional Materials Design',
    ],
  },
  {
    type: 'Consultants',
    subtypes: [
      'Logistics Strategy Consultants',
      'Supply Chain Consultants',
      'Ecommerce Business Consultants',
      'Sustainability Consultants',
      'Third-Party Logistics (3PL) Consultants',
      'Lean and Six Sigma Consultants',
      'Risk Management Consultants',
      'Customer Experience Consultants',
      'Market Entry Strategy Consultants',
      'Creative Consultancy Services',
    ],
  },
];
